//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTrainProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration_date
    {
        public int r_date_id { get; set; }
        public int car_id { get; set; }
        public Nullable<System.DateTime> leave_time { get; set; }
        public Nullable<System.DateTime> entery_time { get; set; }
        public int loc_number { get; set; }
    
        public virtual car car { get; set; }
        public virtual park_place park_place { get; set; }
    }
}
